name: pdnet
services:
  neo4j:
    image: neo4j:5.20-enterprise
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_transaction_total_max=0
      - NEO4J_dbms_security_procedures_unrestricted=gds*
    volumes:
      - ./scripts:/var/lib/neo4j/import/
      - ../neo4j/data:/var/lib/neo4j/data
      - ./plugins:/var/lib/neo4j/plugins

  nestjs:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - "3000:4000"
    depends_on:
      - neo4j
      - postgres
    env_file:
      - backend/.env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    env_file:
      - frontend/.env
    ports:
      - "5000:80"

  gsea:
    build:
      context: backend/gsea
      dockerfile: Dockerfile
    container_name: gsea
    restart: always
    ports:
      - "8000:5000"

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-cache:/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"  
      - "9000:9000"  
      - "9009:9009"   
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-cache:
  postgres-data:
  clickhouse-data: